linkedin_email: "example.user@gmail.com"
linkedin_password: "ChangeMe123!"
total_pages: 2
base_search_url: "https://www.linkedin.com/search/results/companies/?companyHqGeo=%5B%2290009680%22%5D&companySize=%5B%22D%22%2C%22E%22%2C%22F%22%2C%22G%22%5D&origin=FACETED_SEARCH&page="